apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-api-blue
  namespace: fintech
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fintech-api
      version: blue
  template:
    metadata:
      labels:
        app: fintech-api
        version: blue
    spec:
      containers:
      - name: fintech-api
        image: yourdockerhub/fintech-api:v1
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
